# environment: production
allow_from: all

logging:
  type: Logger
  file: /var/log/aurora.log
  level: info

# App specific configurations
authenticator: simple
tokens:
  # lifetime in minutes
  lifetime: 5
