log_file: /tmp/aurora.log # blank for STDOUT
log_level: debug
allow_from: all

# App specific configurations
tokens:
  # lifetime in minutes
  lifetime: 5

# Database configuration
db:
  adapter: mysql
  host: localhost
  username: authenticator
  password: secret
  database: auth
