defaults: &defaults
  adapter: mysql
  host: localhost
  username: aurora_user
  password: password

development:
  database: aurora_development
  <<: *defaults

test:
  database: aurora_test
  <<: *defaults

production:
  database: aurora
  <<: *defaults
